### ISSUE TITLE
Upload of pkgs bigger than 4GB with macOS_Application_PKG_Add.ps1

### ISSUE THREAD

**Issue by falcomenz** [microsoft/mggraph-intune-samples#20]
I've been playing around with the macOS_Application_PKG_Add.ps1 skript and i can successfully upload most of my packages to Intune, but it seems that every pkg bigger than 4gb seems to end in an error. 

I already changed **[UInt32]$BlockSizeMB = 1** to **[Int64]$BlockSizeMB = 1** to get the script start to upload these big files in the first place, but the  Update-MgBetaDeviceAppManagementMobileApp module seems not to work with these large files:

Update-MgBetaDeviceAppManagementMobileApp : {
  "_version": 3,
  "Message": "An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: f604ccdb-398f-431d-b85a-be787957b321 - Url:
[https://fef.msub01.manage.microsoft.com/AppLifecycle_2411/StatelessAppMetadataFEService/deviceAppManagement/mobileApps('277324ca-3b07-4c38-842c-dbc9951f0ba0')?api-version=](https://fef.msub01.manage.microsoft.com/AppLifecycle_2411/StatelessAppMetadataFEService/deviceAppManagement/mobileApps(%27277324ca-3b07-4c38-842c-dbc9951f0ba0%27)?api-version=)
5024-09-03",
  "CustomApiErrorPhrase": "",
  "RetryAfter": null,
  "ErrorSourceService": "",
  "HttpHeaders": "{}"
}
Status: 400 (BadRequest)
ErrorCode: BadRequest
Date: 2024-11-18T12:13:06
Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : a5d7fe0a-5b94-4c2d-938e-20fdc4ee0b50
client-request-id             : f604ccdb-398f-431d-b85a-be787957b321
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"Germany West Central","Slice":"E","Ring":"4","ScaleUnit":"000","RoleInstance":"FR1PEPF0000160F"}}
Date                          : Mon, 18 Nov 2024 12:13:06 GMT
At C:\Users\fmenz_adm\Desktop\macOS_Application_PKG_Add.ps1:149 char:9
        Update-MgBetaDeviceAppManagementMobileApp -MobileAppId $mobil ...
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidOperation: ({ MobileAppId =...raphMobileApp }:<>f__AnonymousType153`3) [Update-MgBetaDe...obileApp_Update], Exception
     FullyQualifiedErrorId : BadRequest,Microsoft.Graph.Beta.PowerShell.Cmdlets.UpdateMgBetaDeviceAppManagementMobileApp_Update

Do you have any idea to solve this?
Thanks! :)

Falco

**Comment by Mahopper** [comment]
Hi @falcomenz 

This is likely due to the Azure Storage URI expiring before the upload completes. I will look to update the sample to:

-  Increase the default block size to 4mb
-  Use a 64bit integer for block size
- Add conditional logic for refreshing the storage URI before it expires

**Comment by Mahopper** [comment]
Hi @falcomenz 

This should now be resolved with this PR: https://github.com/microsoft/mggraph-intune-samples/pull/21

Let us know if you run into any issues- thanks for reporting this!

**Comment by falcomenz** [comment]
Perfect! Thank you so much!
I still had to change the **UploadAzureStorageChunk** just a bit:


```
function UploadAzureStorageChunk($sasUri, $id, $body) {
    $uri = "$sasUri&comp=block&blockid=$id"
    $headers = @{
        "x-ms-blob-type" = "BlockBlob"
        "Content-Type"   = "application/octet-stream"
        "Accept"         = "*/*"
    }

    try {
        Invoke-WebRequest -Headers $headers -Uri $uri -Method Put -Body $body | Out-Null 
    }
    catch {
        Write-Host -ForegroundColor Red "Failed to upload chunk with ID: $id"
        Write-Host -ForegroundColor Red $_.Exception.Message
        throw
    }
} 
```

But now it works perfectly with your newest commit as i just uploaded Adobe Illustrator to Intune 👍 We can now install Adobe Packages as managed Packages without the need of scripts!

**Comment by Mahopper** [comment]
> Perfect! Thank you so much! I still had to change the **UploadAzureStorageChunk** just a bit:
> 
> ```
> function UploadAzureStorageChunk($sasUri, $id, $body) {
>     $uri = "$sasUri&comp=block&blockid=$id"
>     $headers = @{
>         "x-ms-blob-type" = "BlockBlob"
>         "Content-Type"   = "application/octet-stream"
>         "Accept"         = "*/*"
>     }
> 
>     try {
>         Invoke-WebRequest -Headers $headers -Uri $uri -Method Put -Body $body | Out-Null 
>     }
>     catch {
>         Write-Host -ForegroundColor Red "Failed to upload chunk with ID: $id"
>         Write-Host -ForegroundColor Red $_.Exception.Message
>         throw
>     }
> } 
> ```
> 
> But now it works perfectly with your newest commit as i just uploaded Adobe Illustrator to Intune 👍 We can now install Adobe Packages as managed Packages without the need of scripts!

Glad to hear! I'll take a bit of a further look into that function, but I didn't hit any issues in my testing across a few different packages. By chance, is the PKG you were testing with available publicly?

**Comment by falcomenz** [comment]
> Glad to hear! I'll take a bit of a further look into that function, but I didn't hit any issues in my testing across a few different packages. By chance, is the PKG you were testing with available publicly?

Sure thing! i tried this one for example:
https://d20qm7qi07z1wt.cloudfront.net/Adobe_CC2025_Photoshop_26.0_de_DE_MACUNIVERSAL.pkg
